### ISSUE TITLE
cargo run --release fails

### ISSUE THREAD

**Issue by harleypig** [tmahmood/taskwarrior-web#1]
I saw your Reddit post and wanted to give this a try. Your interface looks great to me. `npm install` in the frontend directory went without a hitch. However, the `cargo run --release` fails.

```
$ cargo run --release
   Compiling taskwarrior-web v0.1.0 (/home/harleypig/projects/taskwarrior-web)
error: failed to run custom build command for `taskwarrior-web v0.1.0 (/home/harleypig/projects/taskwarrior-web)`

Caused by:
  process didn't exit successfully: `/home/harleypig/projects/taskwarrior-web/target/release/build/taskwarrior-web-da53464faa98349e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=frontend/

  --- stderr
  thread 'main' panicked at build.rs:7:19:
  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I'm not familiar with rust, but [this line](https://github.com/tmahmood/taskwarrior-web/blob/c4c8e7c4cd885f6b9867bea9343f1b9f59856809/build.rs#L7) shows you're attempting to access a file that doesn't exist; `dist/style.css`.

I tried creating the directory and copying `style.css` from `frontend/css` to `dist` but that didn't change the error message.

**Comment by tmahmood** [comment]
Ah! Sorry, I did not update the documentation. You need to install `tailwindcss-cli` and `rollup`.
