### ISSUE TITLE
Docker image by any chance?

### ISSUE THREAD

**Issue by lxgreen** [tmahmood/taskwarrior-web#3]
Hi @tmahmood

Thanks for this great initiative, looks really good.

Any chance you provide a Docker image to reduce the dependency installation burden?

**Comment by tmahmood** [comment]
Thank you! 

Docker image would be a good idea, I'll set it up

**Comment by tmahmood** [comment]
Hey @lxgreen, 
Docker image is added. Instruction also updated.
